/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/VKe6vdh4pVu
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import React from 'react';
import { Label } from "../../../@/components/ui/label"
import { Textarea } from "../../../@/components/ui/textarea"

export default function Summary3() {
  return (
    <div className="w-full max-w-3xl grid gap-4">
      <div className="grid gap-0.5">
        <h1 className="text-3xl font-bold tracking-tight">Automated Essay Generator</h1>
        <p className="text-gray-500 dark:text-gray-400">Enter your essay below.</p>
      </div>
      <div className="grid gap-4">
        <div className="grid gap-2">
          <Label htmlFor="introduction">Introduction</Label>
          <Textarea className="min-h-[150px]" id="introduction" placeholder="Type your introduction here." />
        </div>
        <div className="grid gap-2">
          <Label htmlFor="body">Body</Label>
          <Textarea className="min-h-[150px]" id="body" placeholder="Type your body here." />
        </div>
        <div className="grid gap-2">
          <Label htmlFor="conclusion">Conclusion</Label>
          <Textarea className="min-h-[150px]" id="conclusion" placeholder="Type your conclusion here." />
        </div>
        <div className="grid gap-2">
          <Label htmlFor="output">Output</Label>
          <Textarea className="bg-gray-100 min-h-[150px]" id="output" readOnly />
        </div>
      </div>
    </div>
  )
}
